steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/test3:$COMMIT_SHA", #cloud-run-source-deploy is artifact registry commit_sha means for any commit
        ".",     #indicates same directory
      ]
    # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/test3:$COMMIT_SHA",
      ]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "hello",    #app name=service name
        "--image",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/test3:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
